# Generated by Django 5.1.1 on 2024-09-10 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='summary',
            field=models.CharField(blank=True, default='Yeni Sohbet', max_length=255),
        ),
    ]
